<h1 style="text-align:center">
 NumPy
</h1>

NumPy es una librería de Python muy usada para trabajar con matemáticas, álgebra y datos numéricos de forma rápida. 
Su nombre viene de “Numerical Python”
Es rapido y eficiente en memoria y simplifica los calculos matematicos complejos

### Intalacion
- pip install numpy



### Operaciones con Matrices

In [ ]:
import numpy as np

# Create a 2x2 Matrix
matrix = np.array([[1,2],[3,4]])
print(matrix)

A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

# Addition
print("Addition:\n", A + B)

# Substraction
print("Substraction:\n", A - B)

# Multiplication
print("Multiplication:\n", A * B)

# Dot Product
print("Dot Product:\n", np.dot(A,B))

# Transpose
print("Transpose of A:\n", A.T)

# Determinant
det = np.linalg.det(A)
print("Determinant:\n", det)

# Inverse
if det != 0:
    inverse = np.linalg.inv(A)
    print("Inverse:\n", inverse)
else:
    print("Matrix is not invertible")



### Entrada de usuario

In [ ]:
import numpy as np

# Function to Create Matrix from User Input
def get_matrix():
    rows = int(input("Enter the number of rows: "))
    cols = int(input("Enter the number of columns: "))
    print("Enter the matrix elements row by row")
    elements = []
    for _ in range(rows):
        row = list(map(float,input().split()))
        elements.append(row)
    return np.array(elements)

# Example Usage
matrix = get_matrix()
print("Matrix:\n", matrix)

### Ejercicio
- Matrix Calculator

In [8]:
import numpy as np

# Function to Create Matrix from User Input
def get_matrix():
    try:
        rows = int(input("Enter the number of rows: "))
        cols = int(input("Enter the number of columns: "))
        print("Enter the matrix elements row by row")
        elements = []
        for _ in range(rows):
            row = list(map(float,input().split()))
            if len(row) != cols:
                raise ValueError("Number of columns doesn't match.")
            elements.append(row)
        return np.array(elements)
    except ValueError as e:
        print("Error:", e)
        return None

# Matrix Operation
def matrix_operations(A,B):
    print("\nMatrix A:\n", A)
    print("\nMatrix B:\n", B)

    try:
        print("\nAddition:\n", A + B)
    except ValueError:
        print("\nAddition: Matrices must have the same dimensions.")

    try:
        print("\nSubstraction:\n", A - B)
    except ValueError:
        print("\nSubstraction: Matrices must have the same dimensions.")

    try:
        print("\nElemetn-wise Multiplication:\n", A * B)
    except ValueError:
        print("\nElemetn-wise Multiplication: Matrices must have the same dimensions.")

    try:
        print("\nDot Product:\n", np.dot(A,B))
    except ValueError:
        print("\nDot Product: Number of column in A must equal the number of rows in B.")

    print("\nTranspose of A:\n", A.T)
    print("\nTranspose of B:\n", B.T)

    try:
        print("\nDeterminant of A:\n", np.linalg.det(A))
    except np.linalg.LinAlgError:
        print("\nDeterminant of A: Not applicable (Matrix must be square).")

    try:
        print("\nInverse of A:\n", np.linalg.inv(A))
    except np.linalg.LinAlgError:
        print("\nInverse of A: Not invertible.")

# Main Program
def main():
    print("Matrix Calculator")
    print("==================")
    print("Input Matrix A:")
    A = get_matrix()
    if A is None:
        return
    
    print("Input Matrix B:")
    B = get_matrix()
    if B is None:
        return
    
    matrix_operations(A,B)

if __name__ == '__main__':
    main()

Matrix Calculator
Input Matrix A:
Enter the matrix elements row by row
Input Matrix B:
Enter the matrix elements row by row

Matrix A:
 [[1. 2.]
 [3. 4.]]

Matrix B:
 [[5. 6.]
 [7. 8.]]

Addition:
 [[ 6.  8.]
 [10. 12.]]

Substraction:
 [[-4. -4.]
 [-4. -4.]]

Elemetn-wise Multiplication:
 [[ 5. 12.]
 [21. 32.]]

Dot Product:
 [[19. 22.]
 [43. 50.]]

Transpose of A:
 [[1. 3.]
 [2. 4.]]

Transpose of B:
 [[5. 7.]
 [6. 8.]]

Determinant of A:
 -2.0000000000000004

Inverse of A:
 [[-2.   1. ]
 [ 1.5 -0.5]]
